### ISSUE TITLE
报异常，但不知道那个字段异常！！！

### ISSUE THREAD

**Issue by xiaobo520** [lisongkun/hygge-imaotai#27]
![image](https://github.com/lisongkun/hygge-imaotai/assets/12594406/7fb66ab8-cff2-4afc-9188-4062768e4ba3)
# 不知道那个配置错了 无法使用  还发现分页错误的问题 。 还需要安装.net6+

**Comment by lisongkun** [comment]
Ok，我下个版本换一下技术栈，现在是手工实现分页的

**Comment by lisongkun** [comment]
更新一下新版试试
