### ISSUE TITLE
预约时提示 异常404

### ISSUE THREAD

**Issue by KelanMai** [lisongkun/hygge-imaotai#29]
9	手机号码	异常	[userId]:1122393127	Call failed with status code 404 (Not Found): GET https://static.moutai519.com.cn/mt-backend/xhr/front/mall/shop/list/slim/v3/708/%E5%B9%BF%E4%B8%9C/10213/1691078400000	2023/8/4 10:09:13

**Comment by lisongkun** [comment]
已修复,请更新最新版

**Comment by KelanMai** [comment]
新版依旧出现404`6	手机号	异常	[userId]:id	Call failed with status code 404 (Not Found): GET https://static.moutai519.com.cn/mt-backend/xhr/front/mall/shop/list/slim/v3/712/%E5%B9%BF%E4%B8%9C/10213/1691337600000	2023/8/7 11:03:21
`
